// import './2-bigO'
// import './4-problem-solving-approach'
// import './5-problem-solving-patterns'
// import './7-recursion'
// import './10-searching-algorithms'
// import './11-sorting-algorithms'
// import './19-linked-lists'
// import './21-stacks-queues'
// import './22-trees'
// import './24-binary-heaps'
import './25-hash-tables'
